name: Special Topics in Learning Analytics
highlighter: pygments

url: http://meefen.github.io/laumn16
shorturl: meefen.github.io/laumn16
baseurl: 

python: false

course:
  title: Learning Analytics in the Knowledge Age
  number: CI 5531
  instructor: Prof. Bodong Chen

authors:
  meefen:
      name: Bodong Chen
      prof: true
      gravatar:
      website: http://meefen.github.io/
      github: meefen
      twitter: bodong_c
      about:  Assistant Professor in learning technologies
  wittgenstein:
      name: Ludwig Wittgenstein
      prof: false
      gravatar:
      website: http://www.tractatus.com
      github:
      twitter:
      about:  Ludwig Wittgenstein discovered that the meaning of E=mc^2 is its use.
  mccarthy:
      name: John McCarthy
      prof: true
      website: http://common-lisp.net/
      about: John McCarthy invented LISP.  Use it.
  jdoe:
      name: John Doe
      prof: false
      about: John Doe gets very strange test emails all the time.
  squw:
      name: Suzie Q
      prof: false
      about: Suzie Q once dated John Fogerty.
